name: MLOps CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v4

    - name: Build Docker image
      run: |
        docker build -t mlops-pipeline -f docker/Dockerfile .

    - name: Run pipeline inside Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/ml_outputs:/app/ml_outputs \
          mlops-pipeline

    - name: Upload pipeline outputs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ml_outputs
        path: ml_outputs
