name: MLOps CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data pipeline
        run: python src/data/data_pipeline.py

      - name: Run model training
        run: python src/model/train.py

      - name: Run evaluation
        run: python src/model/evaluate.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: ml_outputs/model/
